default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: postfixlogviewer_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: postfixlogviewer_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  <<: *default
  database: postfixlogviewer_production
  username: postgres
  password: postgres
  host: localhost
  port: 5432
